### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by orsty3001** [russinnes/py-vox-recorder#1]
I'm trying to run this on a netbook with a celeron 1.6ghz cpu with 8 gb of ram. I get the error below. 

ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
0ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
Device Information:, add proper index # to .py script
Dev#:  0 HDA Intel PCH: ALC236 Analog (hw:0,0)
Dev#:  1 HDA Intel PCH: HDMI 0 (hw:0,3)
Dev#:  2 sysdefault
Dev#:  3 front
Dev#:  4 surround40
Dev#:  5 surround51
Dev#:  6 surround71
Dev#:  7 hdmi
Dev#:  8 pulse
Dev#:  9 dmix
Dev#:  10 default
Segmentation fault (core dumped)

**Comment by russinnes** [comment]
Make sure you put your device index in the python script, it's at the top. I believe the default is 12. In your case, assuming you are using your analog soundcard input, your device would be 0 (from the log output you provided). Disregard the pulseaudio / jack warning messages that you are getting. 

Look for this: 
# Device index of your input
DEVICE_INDEX=12

and change 12 to 0
